# Pages project configuration
pages_build_output_dir = "."  # Or specify your build output directory if different

# Exclusions for large files
[build.upload]
format = "directory"
dir = "."
include = []
exclude = [
  "clouddoc/scene.glb"
]

# If you need environment variables
[env]
# Add any environment variables here if needed
# VAR_NAME = "value"

# If you need preview-specific settings
[env.preview]
# Preview-specific settings go here

# If you need production-specific settings
[env.production]
# Production-specific settings go here