# Required top-level name field for Pages
name = "juliancoy-github-io"

# Pages build configuration
pages_build_output_dir = "."

# Exclusions for large files
[build]
[build.upload]
exclude = [
  "clouddoc"
]

# Environment-specific configurations (if needed)
[env.preview]
# Preview-specific settings

[env.production]
# Production-specific settings